[dataset]
face_data = [
    "jessicali9530/celeba-dataset",
    "rajnishe/facescrub-full",
    "annasvoboda/pubfig83",
    "arnaud58/flickrfaceshq-dataset-ffhq"
    ]

### 0 : Random Identity Sampling
### 1 : Cardinality-Aware Identity Sampling
### 2 : No need for sampling identities
id_option = [1,0,0,2]
private_id = [1000, 200, 50, 0]
size = 64