[classifier]

model_list = [
    'timm/vgg16.tv_in1k', 
    'microsoft/resnet-152', 
    'minchul/cvlface_adaface_ir50_ms1mv2'
    ]

input_size = [224, 224, 112]

optimizer = 'SGD'
learning_rate = 5e-5
momentum = 0.9
weight_decay = 1e-4
batch_size = 64
epoch = 50
log_steps = 50

train_ratio = 0.8
valid_ratio = 0.1
test_ratio = 0.1

is_stratified = true
use_wandb = true
early_stopping = true
upload_hf = true

patience = 10
space_name = 'Face-Classifiers'
seed = 42
deterministic = true

### ImageNet Mean, and Standard deviation
transform_mean = [0.485, 0.456, 0.406]
transform_std = [0.229, 0.224, 0.225]
augment = true

[classifier.pretrain]
enabled = true
dataset = "flwrlabs/celeba"
train_split = "train"
valid_split = "validation"
test_split = "test"
label_column = "label"
image_column = "image"
output_dir = "checkpoints/pretrain"

[generator]
